### ISSUE TITLE
Morning session Code review

### ISSUE THREAD

**Issue by ahzia** [codecaiine/todo-list-app#9]
You did a great job, just a few suggestions:

> Your live link is pointing to readme file, deploy your project to GitHub page and use the link as live link.
You can use `npm gh-pages` for that purpose.

> Separate your HTML, CSS, and JS files in different folders

**Comment by OLIPLICHE** [comment]
Great Job.
Another suggestion to make your link live:  add dist/ at the end of your live demo link.
